version: 1.0.0.{build}
os: Visual Studio 2015

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

before_build:
- cmd: >-
    dotnet restore src\GoalSetter

build_script:
- cmd: >-
    dotnet pack src\GoalSetter --configuration Release --output "artifacts\bin\src\GoalSetter"
    dotnet pack test\GoalSetter.Tests --configuration Release --output "artifacts\bin\test\GoalSetter.Tests"